name: Deploy Quartz site to GitHub Pages
 
on:
  schedule:
    - cron: '0 3 * * *'  # Nightly at 03:00 UTC
  workflow_dispatch:
  push:
permissions:
  contents: write
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Fetch all history for git info
        
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          
      - name: Clone vault repo and sync to content/
        run: |
          git clone https://$GITHUB_ACTOR:${{ secrets.VAULT_TOKEN }}@github.com/ville-solja/Obsidian-Dota.git temp-vault
          rm -rf quartz/content/*
          rsync -av --exclude=package.json --exclude=package-lock.json temp-vault/ content/
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build Quartz
        run: npx quartz build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: quartz/public
